{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 1, "revision": 4, "architecture": "arm64" },
    "classnamespace": "box",
    "rect": [90.0, 90.0, 1160.0, 720.0],
    "openinpresentation": 0,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "boxes": [
      { "box": { "id": "title", "maxclass": "comment", "text": "jit.handpose — native MediaPipe hand landmarks from a Jitter matrix", "fontsize": 20.0, "patching_rect": [30.0, 20.0, 780.0, 30.0] } },
      { "box": { "id": "intro", "maxclass": "comment", "text": "The external retains only the newest waiting frame and performs inference on a worker thread.", "patching_rect": [30.0, 55.0, 760.0, 22.0] } },
      { "box": { "id": "toggle", "maxclass": "toggle", "patching_rect": [30.0, 100.0, 24.0, 24.0] } },
      { "box": { "id": "metro", "maxclass": "newobj", "text": "qmetro 33", "patching_rect": [65.0, 101.0, 70.0, 22.0] } },
      { "box": { "id": "open", "maxclass": "message", "text": "open", "patching_rect": [155.0, 101.0, 42.0, 22.0] } },
      { "box": { "id": "close", "maxclass": "message", "text": "close", "patching_rect": [205.0, 101.0, 42.0, 22.0] } },
      { "box": { "id": "grab", "maxclass": "newobj", "text": "jit.grab @unique 1", "patching_rect": [65.0, 145.0, 120.0, 22.0] } },
      { "box": { "id": "preview", "maxclass": "jit.pwindow", "patching_rect": [30.0, 190.0, 480.0, 360.0] } },
      { "box": { "id": "tracker", "maxclass": "newobj", "text": "jit.handpose 2", "patching_rect": [570.0, 190.0, 105.0, 22.0] } },
      { "box": { "id": "start", "maxclass": "message", "text": "start", "patching_rect": [570.0, 100.0, 42.0, 22.0] } },
      { "box": { "id": "stop", "maxclass": "message", "text": "stop", "patching_rect": [620.0, 100.0, 40.0, 22.0] } },
      { "box": { "id": "status", "maxclass": "message", "text": "status", "patching_rect": [670.0, 100.0, 48.0, 22.0] } },
      { "box": { "id": "reset", "maxclass": "message", "text": "reset", "patching_rect": [728.0, 100.0, 43.0, 22.0] } },
      { "box": { "id": "hands", "maxclass": "message", "text": "hands 2", "patching_rect": [781.0, 100.0, 58.0, 22.0] } },
      { "box": { "id": "thresholds", "maxclass": "message", "text": "thresholds 0.5 0.5 0.5", "patching_rect": [849.0, 100.0, 150.0, 22.0] } },
      { "box": { "id": "background-off", "maxclass": "message", "text": "background 0", "patching_rect": [570.0, 135.0, 92.0, 22.0] } },
      { "box": { "id": "background-on", "maxclass": "message", "text": "background 1", "patching_rect": [672.0, 135.0, 92.0, 22.0] } },
      { "box": { "id": "mirror-off", "maxclass": "message", "text": "mirror 0", "patching_rect": [774.0, 135.0, 65.0, 22.0] } },
      { "box": { "id": "mirror-on", "maxclass": "message", "text": "mirror 1", "patching_rect": [849.0, 135.0, 65.0, 22.0] } },
      { "box": { "id": "landmarks-print", "maxclass": "newobj", "text": "print hand-landmarks", "patching_rect": [570.0, 245.0, 135.0, 22.0] } },
      { "box": { "id": "world-print", "maxclass": "newobj", "text": "print hand-world", "patching_rect": [725.0, 245.0, 110.0, 22.0] } },
      { "box": { "id": "meta-print", "maxclass": "newobj", "text": "print hand-meta", "patching_rect": [855.0, 245.0, 105.0, 22.0] } },
      { "box": { "id": "landmarks-note", "maxclass": "comment", "text": "landmarks <hand> followed by 21 normalized x y z triples", "patching_rect": [570.0, 290.0, 430.0, 22.0] } },
      { "box": { "id": "world-note", "maxclass": "comment", "text": "world <hand> followed by 21 metric x y z triples", "patching_rect": [570.0, 320.0, 430.0, 22.0] } },
      { "box": { "id": "meta-note", "maxclass": "comment", "text": "hands, handedness and status arrive at the third outlet", "patching_rect": [570.0, 350.0, 430.0, 22.0] } },
      { "box": { "id": "status-note", "maxclass": "comment", "text": "status: ready active processing received processed dropped code text", "patching_rect": [570.0, 395.0, 475.0, 22.0] } },
      { "box": { "id": "annotated-preview", "maxclass": "jit.pwindow", "patching_rect": [570.0, 440.0, 320.0, 240.0] } },
      { "box": { "id": "annotated-note", "maxclass": "comment", "text": "Fourth outlet: ARGB annotation; background 0 is transparent (default)", "patching_rect": [905.0, 440.0, 230.0, 52.0] } },
      { "box": { "id": "input-note", "maxclass": "comment", "text": "Input formats: 4-plane ARGB, 3-plane RGB, or 1-plane char grayscale.", "patching_rect": [30.0, 585.0, 520.0, 22.0] } },
      { "box": { "id": "runtime-note", "maxclass": "comment", "text": "Inference is local and CPU-only in this first macOS build.", "patching_rect": [30.0, 615.0, 520.0, 22.0] } },
      { "box": { "id": "model-note", "maxclass": "comment", "text": "The bundled hand_landmarker.task model is found automatically through the package support folder.", "patching_rect": [30.0, 645.0, 700.0, 22.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["toggle", 0], "destination": ["metro", 0] } },
      { "patchline": { "source": ["metro", 0], "destination": ["grab", 0] } },
      { "patchline": { "source": ["open", 0], "destination": ["grab", 0] } },
      { "patchline": { "source": ["close", 0], "destination": ["grab", 0] } },
      { "patchline": { "source": ["grab", 0], "destination": ["preview", 0] } },
      { "patchline": { "source": ["grab", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["start", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["stop", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["status", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["reset", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["hands", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["thresholds", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["background-off", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["background-on", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["mirror-off", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["mirror-on", 0], "destination": ["tracker", 0] } },
      { "patchline": { "source": ["tracker", 0], "destination": ["landmarks-print", 0] } },
      { "patchline": { "source": ["tracker", 1], "destination": ["world-print", 0] } },
      { "patchline": { "source": ["tracker", 2], "destination": ["meta-print", 0] } },
      { "patchline": { "source": ["tracker", 3], "destination": ["annotated-preview", 0] } }
    ]
  }
}
